### ISSUE TITLE
[CTD] Crash on entering The End

### ISSUE THREAD

**Issue by drakray** [Team-Arcanum/Nordic-Arcanum-Issues#2]
Minecraft 1.16.3
Forge 34.1.25(also with Forge 34.1.42)
Arcanum API 0.3.0
Nordic Arcanum 0.5.0
buncha others

https://pastebin.com/6zD1QRRa

Removing Lake Generation in Config allow for entering The End
Haven't tried entering it with lake disabled, re-enabling Lake, then generating more End

```
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_251] {}
	at com.lordskittles.nordicarcanum.common.world.feature.decorators.DecoratorUndergroundLake.func_241857_a(DecoratorUndergroundLake.java:30) ~[?:?] {re:classloading}
	at com.lordskittles.nordicarcanum.common.world.feature.decorators.DecoratorUndergroundLake.func_241857_a(DecoratorUndergroundLake.java:17) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.placement.ConfiguredPlacement.func_242876_a(SourceFile:24) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:22) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:254) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:77) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:522) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_251] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_251] {}
```

**Comment by LordSkittles** [comment]
Hi Darkray! 

Thanks for reporting this, investigating now! Should be fixed in the next version

**Comment by drakray** [comment]
The End seems to be fixed, now I got https://pastebin.com/QFhE2vuk when trying to make a Superflat:TheVoid(which is the same crash)

**Comment by LordSkittles** [comment]
Are you actively trying to break my mod? :P If so... THANK YOU! haha!

This is fixed in the next version, the next version is a HUGE update that will change a bunch of world gen, textures and other things... might take a couple of days to be released.

**Comment by drakray** [comment]
I'm a coder myself, I know the importance of having tester to make everything catch fire and explode XDXD

On an unrelated note, will there be a way to get/move Statue, because as of now mining them drop nothing(even with SilkTouch), and they are not craftable.
