### ISSUE TITLE
Error during loading mod (1.16.3)

### ISSUE THREAD

**Issue by EnigmaFlame** [Team-Arcanum/Nordic-Arcanum-Issues#4]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[?:?] {re:classloading}
-- MOD nordicarcanum --
Details:
	Mod File: nordicarcanum-1.16.3-0.6.1.jar
	Failure message: Nordic Arcanum (nordicarcanum) encountered an error during the load_registries event phase
		java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
	Mod Version: 0.6.1
	Mod Issue URL: https://github.com/Team-Arcanum/Nordic-Arcanum/issues
	Exception message: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
Stacktrace:
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at com.lordskittles.nordicarcanum.common.registry.FoliageType.lambda$registerFoliageTypes$0(FoliageType.java:34) ~[?:?] {re:classloading}
	at com.lordskittles.nordicarcanum.common.registry.FoliageType$$Lambda$7169/2139428966.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at com.lordskittles.nordicarcanum.common.registry.FoliageType.registerFoliageTypes(FoliageType.java:34) ~[?:?] {re:classloading}
	at com.lordskittles.nordicarcanum.common.events.RegistryEvents.onRegisterTrunkPlacers(RegistryEvents.java:73) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_402_RegistryEvents_onRegisterTrunkPlacers_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:34.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3425/1160651280.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:242) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:195) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$3154/240931578.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$3155/1631805946.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.42.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$491/1577067350.call(Unknown Source) [forge-1.16.3-34.1.42.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

**Comment by LordSkittles** [comment]
In order for me to help you I need more information, please provide me with the version of Forge you are using
